const fs = require("fs");
const path = require("path");
const config = require("../config/config");
const rpgSystem = require("./rpgSystem");
const { createStatusQuoted } = require("./statusCard");

const DB_PATH = path.join(__dirname, "..", "database", "rpg.json");
const LEGACY_COMMANDS = [
  "cacar", "ficha", "loja", "lojapets", "minerar", "pets",
  "rankgold", "ranklevel", "registro", "roubar", "set-gold", "ver-ficha"
];

const ITEMS = {
  "pocao": { label: "Poção", type: "consumivel", price: 120, heal: 40, rarity: "comum" },
  "eter": { label: "Éter", type: "consumivel", price: 140, mana: 35, rarity: "comum" },
  "refeicao": { label: "Refeição", type: "consumivel", price: 80, heal: 25, rarity: "comum" },
  "madeira": { label: "Madeira", type: "material", price: 18, rarity: "comum" },
  "ferro": { label: "Ferro", type: "material", price: 35, rarity: "comum" },
  "prata": { label: "Prata", type: "material", price: 70, rarity: "incomum" },
  "cristal": { label: "Cristal", type: "material", price: 95, rarity: "raro" },
  "erva": { label: "Erva", type: "material", price: 20, rarity: "comum" },
  "erva-rara": { label: "Erva rara", type: "material", price: 80, rarity: "raro" },
  "peixe": { label: "Peixe", type: "material", price: 25, rarity: "comum" },
  "argila": { label: "Argila", type: "material", price: 16, rarity: "comum" },
  "sucata": { label: "Sucata", type: "material", price: 12, rarity: "comum" },
  "fragmento": { label: "Fragmento antigo", type: "material", price: 110, rarity: "raro" },
  "concha": { label: "Concha", type: "material", price: 28, rarity: "comum" },
  "obsidiana": { label: "Obsidiana", type: "material", price: 180, rarity: "epico" },
  "gelo-eterno": { label: "Gelo eterno", type: "material", price: 160, rarity: "epico" },
  "runa": { label: "Runa", type: "material", price: 145, rarity: "raro" },
  "essencia": { label: "Essência", type: "material", price: 300, rarity: "epico" },
  "bau": { label: "Baú", type: "especial", price: 220, rarity: "raro" },
  "espada-ferro": { label: "Espada de ferro", type: "arma", price: 600, attack: 8, rarity: "incomum" },
  "arco-runa": { label: "Arco rúnico", type: "arma", price: 1500, attack: 15, rarity: "raro" },
  "armadura-ferro": { label: "Armadura de ferro", type: "armadura", price: 750, defense: 7, rarity: "incomum" },
  "manto-runa": { label: "Manto rúnico", type: "armadura", price: 1600, defense: 12, rarity: "raro" },
  "anel-agilidade": { label: "Anel de agilidade", type: "acessorio", price: 900, agility: 5, rarity: "raro" }
};

const RECIPES = {
  "pocao": { ingredients: { "erva": 2, "cristal": 1 }, amount: 1 },
  "refeicao": { ingredients: { "peixe": 1, "erva": 1 }, amount: 2 },
  "espada-ferro": { ingredients: { "ferro": 4, "madeira": 1 }, amount: 1 },
  "armadura-ferro": { ingredients: { "ferro": 6 }, amount: 1 },
  "arco-runa": { ingredients: { "madeira": 4, "runa": 2, "cristal": 2 }, amount: 1 }
};

const CLASSES = {
  "arqueiro": { dano: 2, defesa: 0, agilidade: 4, mana: 0, text: "alta agilidade e crítico" },
  "guerreiro": { dano: 4, defesa: 3, agilidade: 0, mana: 0, text: "dano físico e defesa" },
  "mago": { dano: 2, defesa: 0, agilidade: 0, mana: 15, text: "mana alta e habilidades" },
  "guardiao": { dano: 0, defesa: 6, agilidade: -1, mana: 5, text: "defesa e proteção" },
  "ladino": { dano: 3, defesa: 0, agilidade: 5, mana: 0, text: "agilidade e golpes críticos" }
};

const SKILLS = {
  "golpe-duplo": { cost: 400, mana: 15, power: 1.55, minLevel: 3 },
  "flecha-precisa": { cost: 500, mana: 18, power: 1.75, minLevel: 5 },
  "barreira": { cost: 550, mana: 20, power: 0, defense: 10, minLevel: 6 },
  "explosao-arcana": { cost: 800, mana: 28, power: 2.1, minLevel: 10 },
  "passo-sombra": { cost: 700, mana: 22, power: 1.7, dodge: true, minLevel: 8 }
};

const QUESTS = {
  q1: { label: "Explorador iniciante", stat: "exploracoes", target: 5, gold: 350, xp: 180 },
  q2: { label: "Coletor dedicado", stat: "coletas", target: 8, gold: 420, xp: 210 },
  q3: { label: "Combatente", stat: "vitorias", target: 4, gold: 600, xp: 300 },
  q4: { label: "Artesão", stat: "crafts", target: 3, gold: 500, xp: 240 }
};

const ZONES = {
  arredores: 1, floresta: 1, praia: 4, caverna: 3, ruinas: 5, pantano: 7,
  deserto: 9, montanha: 11, templo: 13, geleira: 15, vulcao: 18
};

const MONSTERS = [
  { name: "Slime cinzento", min: 1, hp: 45, attack: 9, gold: 55, xp: 45 },
  { name: "Lobo das cinzas", min: 3, hp: 75, attack: 13, gold: 85, xp: 70 },
  { name: "Guardião das ruínas", min: 6, hp: 120, attack: 18, gold: 130, xp: 110 },
  { name: "Golem de cristal", min: 10, hp: 180, attack: 24, gold: 190, xp: 160 },
  { name: "Sentinela vulcânica", min: 16, hp: 270, attack: 32, gold: 300, xp: 240 }
];

const BOSSES = [
  { name: "Colosso de Ferro", hp: 1200, attack: 28, reward: 900, xp: 500 },
  { name: "Serpente Rúnica", hp: 1600, attack: 34, reward: 1200, xp: 650 },
  { name: "Titã de Obsidiana", hp: 2200, attack: 42, reward: 1700, xp: 850 }
];

const SMALLCAPS = {
  a:"ᴀ", b:"ʙ", c:"ᴄ", d:"ᴅ", e:"ᴇ", f:"ғ", g:"ɢ", h:"ʜ", i:"ɪ", j:"ᴊ",
  k:"ᴋ", l:"ʟ", m:"ᴍ", n:"ɴ", o:"ᴏ", p:"ᴘ", q:"ǫ", r:"ʀ", t:"ᴛ", u:"ᴜ",
  v:"ᴠ", w:"ᴡ", y:"ʏ", z:"ᴢ"
};

function stylize(text) {
  return String(text).split(/(`[^`]*`)/g).map((part) => {
    if (part.startsWith("`") && part.endsWith("`")) return part;
    return part.replace(/[A-Za-z]/g, (ch) => SMALLCAPS[ch.toLowerCase()] || ch.toLowerCase());
  }).join("");
}

function clone(value) { return JSON.parse(JSON.stringify(value)); }
function ensureDb() { fs.mkdirSync(path.dirname(DB_PATH), { recursive: true }); if (!fs.existsSync(DB_PATH)) fs.writeFileSync(DB_PATH, JSON.stringify({ usuarios: {} }, null, 2)); }
function loadDb() { ensureDb(); let db; try { db = JSON.parse(fs.readFileSync(DB_PATH, "utf8")); } catch { db = { usuarios: {} }; } if (!db || typeof db !== "object") db = { usuarios: {} }; if (!db.usuarios || typeof db.usuarios !== "object") db.usuarios = {}; if (!db.guildas || typeof db.guildas !== "object") db.guildas = {}; if (!Array.isArray(db.mercado)) db.mercado = []; if (!db.rpgConfig || typeof db.rpgConfig !== "object") db.rpgConfig = {}; if (!db.rpgBans || typeof db.rpgBans !== "object") db.rpgBans = {}; if (!db.bosses || typeof db.bosses !== "object") db.bosses = {}; if (!db.raids || typeof db.raids !== "object") db.raids = {}; if (!db.duelos || typeof db.duelos !== "object") db.duelos = {}; if (!db.eventoGlobal || typeof db.eventoGlobal !== "object") db.eventoGlobal = {}; return db; }
function saveDb(db) { ensureDb(); const temp = `${DB_PATH}.${process.pid}.${Date.now()}.tmp`; fs.writeFileSync(temp, JSON.stringify(db, null, 2)); fs.renameSync(temp, DB_PATH); }
function defaultStats() { return { acoes: 0, batalhas: 0, vitorias: 0, derrotas: 0, coletas: 0, exploracoes: 0, crafts: 0, duelosV: 0, duelosD: 0, bossDamage: 0, goldEarned: 0 }; }

function normalizeUser(user, id, pushName = "Aventureiro") {
  if (!user || typeof user !== "object") user = {};
  const defaults = { lid:id, pushName, rpgNome:pushName, level:1, xp:0, xpPatente:0, classe:"Arqueiro", gold:0, banco:0, patente:"Recruta", prestigio:0, arma:[], espada:[], pet:[], petEquipado:null, escudo:[], itens:[], vida:90, vidaMax:90, mana:40, manaMax:40, stamina:100, staminaMax:100, dano:20, defesa:8, agilidade:25, critico:10, habilidades:[], mochila:{}, equipamentos:{arma:null,armadura:null,acessorio:null}, equipamentoBonus:{dano:0,defesa:0,agilidade:0}, cooldowns:{}, buffs:[], conquistas:[], titulos:["Recruta"], tituloAtivo:"Recruta", especializacao:null, zona:"arredores", combate:null, guilda:null, amigosRpg:[], party:[], missaoAtiva:null, recompensasRecentes:[], stats:defaultStats(), ultimoTreino:null, ultimaCaca:null, ultimaMina:null, renome:0 };
  for (const [key,value] of Object.entries(defaults)) if (user[key] === undefined || user[key] === null) user[key] = clone(value);
  if (!user.mochila || typeof user.mochila !== "object" || Array.isArray(user.mochila)) user.mochila = {};
  if (!user.equipamentos || typeof user.equipamentos !== "object") user.equipamentos = clone(defaults.equipamentos);
  if (!user.equipamentoBonus || typeof user.equipamentoBonus !== "object") user.equipamentoBonus = clone(defaults.equipamentoBonus);
  if (!user.cooldowns || typeof user.cooldowns !== "object") user.cooldowns = {};
  if (!Array.isArray(user.buffs)) user.buffs = [];
  if (!Array.isArray(user.conquistas)) user.conquistas = [];
  if (!Array.isArray(user.titulos)) user.titulos = ["Recruta"];
  if (!Array.isArray(user.habilidades)) user.habilidades = [];
  if (!Array.isArray(user.amigosRpg)) user.amigosRpg = [];
  if (!Array.isArray(user.party)) user.party = [];
  if (!Array.isArray(user.recompensasRecentes)) user.recompensasRecentes = [];
  user.stats = { ...defaultStats(), ...(user.stats || {}) };
  user.vida = Math.min(Number(user.vida) || 0, Number(user.vidaMax) || 90);
  user.mana = Math.min(Number(user.mana) || 0, Number(user.manaMax) || 40);
  return user;
}

function senderId(msg, from) { return msg?.key?.participantAlt || msg?.key?.participant || msg?.key?.remoteJidAlt || msg?.key?.remoteJid || from; }
function pushName(msg) { return String(msg?.pushName || "Aventureiro").replace(/[\r\n]+/g, " ").slice(0, 60); }
function contextInfoOf(msg) { return msg?.message?.extendedTextMessage?.contextInfo || msg?.message?.imageMessage?.contextInfo || msg?.message?.videoMessage?.contextInfo || msg?.message?.documentMessage?.contextInfo || {}; }
function targetId(msg) { const ctx = contextInfoOf(msg); const mentioned = Array.isArray(ctx?.mentionedJid) ? ctx.mentionedJid[0] : null; return mentioned || ctx?.participant || null; }
function groupConfig(db, from) { if (!db.rpgConfig[from]) db.rpgConfig[from] = { goldMultiplier:1, xpMultiplier:1, pvp:true }; return db.rpgConfig[from]; }
function addItem(user,item,qty=1){const key=String(item||"").toLowerCase();const n=Math.max(1,Math.floor(Number(qty)||1));user.mochila[key]=(Number(user.mochila[key])||0)+n;}
function removeItem(user,item,qty=1){const key=String(item||"").toLowerCase();const n=Math.max(1,Math.floor(Number(qty)||1));const have=Number(user.mochila[key])||0;if(have<n)return false;const left=have-n;if(left>0)user.mochila[key]=left;else delete user.mochila[key];return true;}
function itemCount(user,item){return Number(user.mochila[String(item||"").toLowerCase()])||0;}
function randomInt(min,max){min=Math.floor(min);max=Math.floor(max);return Math.floor(Math.random()*(max-min+1))+min;}
function xpNeeded(user){return 100+(Number(user.level)||1)*55;}
function gainXp(user,amount){let gainedLevels=0;user.xp=(Number(user.xp)||0)+Math.max(0,Math.floor(amount));while(user.xp>=xpNeeded(user)){user.xp-=xpNeeded(user);user.level+=1;user.vidaMax+=4;user.manaMax+=2;user.vida=user.vidaMax;user.mana=user.manaMax;gainedLevels+=1;}return gainedLevels;}
function reward(user,gold,xp,cfg={goldMultiplier:1,xpMultiplier:1}){const g=Math.max(0,Math.floor(gold*(Number(cfg.goldMultiplier)||1)));const x=Math.max(0,Math.floor(xp*(Number(cfg.xpMultiplier)||1)));user.gold+=g;user.stats.goldEarned+=g;const levels=gainXp(user,x);user.recompensasRecentes.unshift({gold:g,xp:x,at:Date.now()});user.recompensasRecentes=user.recompensasRecentes.slice(0,10);return{gold:g,xp:x,levels};}
function cooldown(user,key,durationMs){const now=Date.now();const until=Number(user.cooldowns[key])||0;if(until>now)return until-now;user.cooldowns[key]=now+durationMs;return 0;}
function formatMs(ms){const sec=Math.max(0,Math.ceil(ms/1000));const min=Math.floor(sec/60);const s=sec%60;if(min>=60){const h=Math.floor(min/60);return`${h}h ${min%60}m`;}return min?`${min}m ${s}s`:`${s}s`;}
function addAchievement(user,id,title){if(!user.conquistas.includes(id)){user.conquistas.push(id);if(!user.titulos.includes(title))user.titulos.push(title);return true;}return false;}
function checkAchievements(user){const got=[];if(user.stats.exploracoes>=10&&addAchievement(user,"explorador10","Explorador"))got.push("Explorador");if(user.stats.vitorias>=10&&addAchievement(user,"vitorias10","Combatente"))got.push("Combatente");if(user.stats.coletas>=25&&addAchievement(user,"coletas25","Coletor"))got.push("Coletor");if(user.level>=20&&addAchievement(user,"nivel20","Veterano"))got.push("Veterano");if(user.prestigio>=1&&addAchievement(user,"prestigio1","Ascendente"))got.push("Ascendente");return got;}
function fmtUser(user){return user.rpgNome||user.pushName||"Aventureiro";}
async function send(conn,from,msg,text){return conn.sendMessage(from,{text:stylize(text)},{quoted:createStatusQuoted(msg)});}
function requireTargetUser(db,msg){const id=targetId(msg);if(!id||!db.usuarios[id])return{error:"Marque ou responda a um jogador registrado."};db.usuarios[id]=normalizeUser(db.usuarios[id],id,db.usuarios[id].pushName||"Aventureiro");return{id,user:db.usuarios[id]};}
function sortedInventory(user){return Object.entries(user.mochila).filter(([,q])=>Number(q)>0).sort((a,b)=>a[0].localeCompare(b[0]));}
function effectiveAttack(user){return(Number(user.dano)||0)+(Number(user.equipamentoBonus?.dano)||0);}
function effectiveDefense(user){const now=Date.now();user.buffs=(user.buffs||[]).filter((b)=>!b.until||b.until>now);const temp=user.buffs.reduce((sum,b)=>sum+(Number(b.defense)||0),0);return(Number(user.defesa)||0)+(Number(user.equipamentoBonus?.defesa)||0)+temp;}
function rebuildEquipmentBonus(user){const bonus={dano:0,defesa:0,agilidade:0};for(const itemName of Object.values(user.equipamentos||{})){if(!itemName)continue;const item=ITEMS[itemName];if(!item)continue;bonus.dano+=item.attack||0;bonus.defesa+=item.defense||0;bonus.agilidade+=item.agility||0;}user.equipamentoBonus=bonus;}
function categories(catalog){const result={};for(const item of catalog)(result[item.category]||=[]).push(item.name);return result;}

function infoText(topic,user,db,from,args,catalog){const prefix=config.prefix||".";const cats=categories(catalog);switch(topic){
case"guide":return`📘 *GUIA RPG GRIMMJOW*\n\n1. Ative o RPG no grupo com \`${prefix}rpgsystem on\` (admin).\n2. Crie sua ficha com \`${prefix}registro\`.\n3. Consulte \`${prefix}ficha\`, \`${prefix}atributos\` e \`${prefix}inventario\`.\n4. Ganhe recursos com trabalho, coleta, exploração, caça e missões.\n5. Use o gold em itens, banco, mercado, equipamentos e evolução.\n6. Aprenda habilidades, escolha classe/especialização e enfrente monstros, chefes e raids.\n7. Crie guildas, monte grupos de aventura e participe do PvP quando habilitado.\n8. Admins podem usar \`${prefix}rpgadmin\` e \`${prefix}rpgset\`.\n9. Use \`${prefix}rpgcomandos categoria\` para filtrar comandos.\n\nCategorias: informação, economia, progressão, aventura, combate, social e administração.\nO sistema possui 150 comandos de RPG contando os 12 comandos clássicos já existentes.`;
case"commands":{const requested=String(args[0]||"").toLowerCase();if(requested&&cats[requested])return`📚 *RPG — ${requested}*\n\n${cats[requested].map((n)=>`• \`${prefix}${n}\``).join("\n")}`;const blocks=Object.keys(cats).map((cat)=>`*${cat}* (${cats[cat].length})\n${cats[cat].map((n)=>`\`${prefix}${n}\``).join(" · ")}`);blocks.push(`*clássicos* (${LEGACY_COMMANDS.length})\n${LEGACY_COMMANDS.map((n)=>`\`${prefix}${n}\``).join(" · ")}`);return`📚 *COMANDOS RPG — 150*\n\n${blocks.join("\n\n")}`;}
case"stats":return`📊 *ESTATÍSTICAS DE ${fmtUser(user)}*\n• ações: ${user.stats.acoes}\n• batalhas: ${user.stats.batalhas}\n• vitórias: ${user.stats.vitorias}\n• derrotas: ${user.stats.derrotas}\n• explorações: ${user.stats.exploracoes}\n• coletas: ${user.stats.coletas}\n• crafts: ${user.stats.crafts}\n• vitórias PvP: ${user.stats.duelosV}\n• dano em bosses: ${user.stats.bossDamage}\n• gold obtido: ${user.stats.goldEarned}`;
case"attributes":return`⚔️ *ATRIBUTOS*\n• vida: ${user.vida}/${user.vidaMax}\n• mana: ${user.mana}/${user.manaMax}\n• stamina: ${user.stamina}/${user.staminaMax}\n• dano: ${effectiveAttack(user)}\n• defesa: ${effectiveDefense(user)}\n• agilidade: ${user.agilidade+(user.equipamentoBonus?.agilidade||0)}\n• crítico: ${user.critico}%\n• level: ${user.level} (${user.xp}/${xpNeeded(user)} XP)`;
case"inventory":{const entries=sortedInventory(user);const legacy=Array.isArray(user.itens)?user.itens.length:0;return`🎒 *INVENTÁRIO*\n${entries.length?entries.map(([k,q])=>`• \`${k}\` x${q}`).join("\n"):"• mochila vazia"}\n• itens clássicos: ${legacy}`;}
case"equipment":return`🛡️ *EQUIPAMENTOS*\n• arma: ${user.equipamentos.arma||"nenhuma"}\n• armadura: ${user.equipamentos.armadura||"nenhuma"}\n• acessório: ${user.equipamentos.acessorio||"nenhum"}\n• bônus: +${user.equipamentoBonus.dano} dano / +${user.equipamentoBonus.defesa} defesa / +${user.equipamentoBonus.agilidade} agilidade`;
case"skills":return`✨ *HABILIDADES*\n${user.habilidades.length?user.habilidades.map((h)=>`• \`${h}\``).join("\n"):"• nenhuma aprendida"}\n\nDisponíveis: ${Object.keys(SKILLS).map((h)=>`\`${h}\``).join(" · ")}`;
case"quests":return user.missaoAtiva?`📜 *MISSÃO ATIVA*\n• ${user.missaoAtiva.label}\n• progresso: ${Math.max(0,user.stats[user.missaoAtiva.stat]-user.missaoAtiva.base)}/${user.missaoAtiva.target}`:`📜 Você não possui missão ativa. Use \`${prefix}missao\`.`;
case"achievements":return`🏆 *CONQUISTAS*\n${user.conquistas.length?user.conquistas.map((x)=>`• ${x}`).join("\n"):"• nenhuma ainda"}`;
case"collection":return`🧰 *COLEÇÃO*\n• tipos na mochila: ${sortedInventory(user).length}\n• pets clássicos: ${Array.isArray(user.pet)?user.pet.length:0}\n• habilidades: ${user.habilidades.length}\n• títulos: ${user.titulos.length}`;
case"titles":return`🎖️ *TÍTULOS*\n• ativo: ${user.tituloAtivo}\n${user.titulos.map((t)=>`• \`${t}\``).join("\n")}`;
case"buffs":return`🔮 *BUFFS*\n${user.buffs.length?user.buffs.map((b)=>`• ${b.name} — ${formatMs(Math.max(0,b.until-Date.now()))}`).join("\n"):"• nenhum ativo"}`;
case"cooldowns":{const active=Object.entries(user.cooldowns).filter(([,until])=>Number(until)>Date.now());return`⏱️ *COOLDOWNS*\n${active.length?active.map(([k,v])=>`• ${k}: ${formatMs(v-Date.now())}`).join("\n"):"• tudo disponível"}`;}
case"classinfo":{const key=String(user.classe||"Arqueiro").toLowerCase();const c=CLASSES[key]||CLASSES.arqueiro;return`🧙 *CLASSE: ${user.classe}*\n• estilo: ${c.text}\n• especialização: ${user.especializacao||"nenhuma"}`;}
case"rankinfo":return`🪖 *PATENTE*\n• atual: ${user.patente}\n• XP de patente: ${user.xpPatente||0}\n• prestígio: ${user.prestigio}`;
case"iteminfo":{const key=String(args[0]||"").toLowerCase();const item=ITEMS[key];if(!item)return`Item não encontrado. Use \`${prefix}receitas\` ou \`${prefix}compraritem\` para ver itens conhecidos.`;return`📦 *${item.label}*\n• id: \`${key}\`\n• tipo: ${item.type}\n• raridade: ${item.rarity}\n• preço base: ${item.price} gold`;}
case"petinfo":return`🐾 *PET*\n• equipado: ${user.petEquipado||"nenhum"}\n• pets clássicos: ${Array.isArray(user.pet)?user.pet.length:0}`;
case"map":return`🗺️ *MAPA*\n${Object.entries(ZONES).map(([z,l])=>`• \`${z}\` — level ${l}+`).join("\n")}\n• local atual: ${user?.zona||"arredores"}`;
case"biomes":return`🌍 *BIOMAS*\n${Object.entries(ZONES).map(([z,l])=>`• ${z}: level ${l}+`).join("\n")}`;
case"monsters":return`👾 *MONSTROS*\n${MONSTERS.map((m)=>`• ${m.name} — level ${m.min}+`).join("\n")}`;
case"bosses":return`👑 *BOSSES*\n${BOSSES.map((b)=>`• ${b.name} — ${b.hp} HP`).join("\n")}`;
case"recipes":return`🛠️ *RECEITAS*\n${Object.entries(RECIPES).map(([name,r])=>`• \`${name}\`: ${Object.entries(r.ingredients).map(([i,q])=>`${i} x${q}`).join(" + ")}`).join("\n")}`;
case"rarities":return`💎 *RARIDADES*\n• comum\n• incomum\n• raro\n• épico\n• lendário\n\nRaridades maiores tendem a ter maior valor e bônus.`;
case"economy":return`💰 *ECONOMIA RPG*\n• gold na carteira pode ser gasto ou transferido.\n• banco protege seu saldo entre atividades.\n• mercado permite anúncios entre jogadores.\n• materiais podem ser vendidos, desmontados ou usados em craft.`;
case"rules":return`📜 *REGRAS RPG*\n• sem exploração de bugs ou duplicação de itens.\n• PvP respeita a configuração do grupo.\n• ações administrativas ficam restritas às permissões do bot.\n• resultados usam cooldowns para manter equilíbrio.\n• o RPG é recreativo e não envolve dinheiro real.`;
default:return"Informação indisponível.";}}

function gatherAction(def,user,cfg){const wait=cooldown(user,def.name,def.cooldown||600000);if(wait)return{text:`Ação em espera por ${formatMs(wait)}.`,changed:true};const g=randomInt(def.reward?.[0]||20,def.reward?.[1]||80);const x=randomInt(def.xp?.[0]||10,def.xp?.[1]||35);if(def.item)addItem(user,def.item,1);user.stats.coletas+=1;user.stats.acoes+=1;const r=reward(user,g,x,cfg);return{text:`Você conseguiu ${r.gold} gold e ${r.xp} XP${def.item?`, além de \`${def.item}\` x1`:""}.`,changed:true};}
function adventureAction(def,user,cfg){if(user.level<(def.level||1))return{text:`Esta região exige level ${def.level}.`,changed:false};const wait=cooldown(user,def.name,600000);if(wait)return{text:`Você poderá explorar novamente em ${formatMs(wait)}.`,changed:true};user.zona=def.zone||user.zona;user.stats.exploracoes+=1;user.stats.acoes+=1;const g=randomInt(def.reward?.[0]||35,def.reward?.[1]||120);const x=randomInt(def.xp?.[0]||20,def.xp?.[1]||60);if(def.item)addItem(user,def.item,1);if(Math.random()<0.08)addItem(user,"bau",1);const r=reward(user,g,x,cfg);return{text:`Exploração em ${def.zone}: +${r.gold} gold, +${r.xp} XP${def.item?` e \`${def.item}\` x1`:""}.`,changed:true};}
function monsterForLevel(level){const eligible=MONSTERS.filter((m)=>level>=m.min);return clone(eligible[Math.floor(Math.random()*eligible.length)]||MONSTERS[0]);}
function enemyStrike(user,enemy){if(user.combate?.dodge){user.combate.dodge=false;if(Math.random()<0.55)return 0;}const def=effectiveDefense(user)+(user.combate?.defending?8:0);if(user.combate)user.combate.defending=false;const damage=Math.max(1,Math.floor(enemy.attack-def*0.35+randomInt(-2,3)));user.vida=Math.max(0,user.vida-damage);return damage;}

async function execute(def,ctx){const{conn,msg,args=[],from,catalog=[]}=ctx;const prefix=config.prefix||".";const db=loadDb();const id=senderId(msg,from);const staticAllowed=new Set(["rpgguia","rpgcomandos","mapa","biomas","monstros","bosses","receitas","raridades","economia","regrasrpg","rpgadmin","rpgset"]);const adminKinds=def.category==="administracao";if(from?.endsWith("@g.us")&&!staticAllowed.has(def.name)&&!adminKinds&&!rpgSystem.isRpgAtivo(from))return send(conn,from,msg,`O sistema RPG está desativado neste grupo. Um admin pode usar \`${prefix}rpgsystem on\`.`);if(db.rpgBans[id]&&!adminKinds&&!staticAllowed.has(def.name))return send(conn,from,msg,"Seu acesso ao RPG está bloqueado pela administração.");let user=db.usuarios[id];const freeWithoutRegistration=new Set(["rpgguia","rpgcomandos","mapa","biomas","monstros","bosses","receitas","raridades","economia","regrasrpg","rpgadmin","rpgset"]);if(!user&&!freeWithoutRegistration.has(def.name)&&!adminKinds)return send(conn,from,msg,`Você ainda não possui ficha. Use \`${prefix}registro\` primeiro.`);if(user){user=normalizeUser(user,id,pushName(msg));db.usuarios[id]=user;}const cfg=groupConfig(db,from);if(def.kind==="info")return send(conn,from,msg,infoText(def.topic,user,db,from,args,catalog));let result=null;

if(def.kind==="daily"){const wait=cooldown(user,"diario",20*60*60*1000);if(wait)result={text:`Sua recompensa diária volta em ${formatMs(wait)}.`,changed:true};else{const r=reward(user,randomInt(180,320),randomInt(80,140),cfg);addItem(user,"pocao",1);user.stats.acoes+=1;result={text:`Recompensa diária: +${r.gold} gold, +${r.xp} XP e \`pocao\` x1.`,changed:true};}}
else if(def.kind==="gather")result=gatherAction(def,user,cfg);
else if(def.kind==="collect"){const materials=["madeira","ferro","erva","peixe","argila","sucata","cristal"];const item=materials[randomInt(0,materials.length-1)];result=gatherAction({...def,item,reward:[25,95],xp:[15,40],cooldown:480000},user,cfg);}
else if(def.kind==="sell"){const item=String(args[0]||"").toLowerCase();const qty=Math.max(1,Math.floor(Number(args[1])||1));const meta=ITEMS[item];if(!meta)result={text:`Item desconhecido. Consulte \`${prefix}iteminfo item\`.`,changed:false};else if(!removeItem(user,item,qty))result={text:`Você não possui \`${item}\` x${qty}.`,changed:false};else{const total=Math.max(1,Math.floor(meta.price*0.55))*qty;user.gold+=total;user.stats.goldEarned+=total;result={text:`Venda concluída: \`${item}\` x${qty} por ${total} gold.`,changed:true};}}
else if(def.kind==="buy"){const item=String(args[0]||"").toLowerCase();const qty=Math.max(1,Math.min(50,Math.floor(Number(args[1])||1)));const meta=ITEMS[item];if(!meta)result={text:`Item desconhecido. Itens: ${Object.keys(ITEMS).map((x)=>`\`${x}\``).join(" · ")}`,changed:false};else{const total=meta.price*qty;if(user.gold<total)result={text:`Gold insuficiente. Custo: ${total}.`,changed:false};else{user.gold-=total;addItem(user,item,qty);result={text:`Compra concluída: \`${item}\` x${qty} por ${total} gold.`,changed:true};}}}
else if(def.kind==="use"){const item=String(args[0]||"").toLowerCase();const meta=ITEMS[item];if(!meta||meta.type!=="consumivel")result={text:"Informe um consumível válido.",changed:false};else if(!removeItem(user,item,1))result={text:`Você não possui \`${item}\`.`,changed:false};else{if(meta.heal)user.vida=Math.min(user.vidaMax,user.vida+meta.heal);if(meta.mana)user.mana=Math.min(user.manaMax,user.mana+meta.mana);result={text:`Você usou \`${item}\`. Vida ${user.vida}/${user.vidaMax}, mana ${user.mana}/${user.manaMax}.`,changed:true};}}
else if(def.kind==="equip"){const item=String(args[0]||"").toLowerCase();const meta=ITEMS[item];if(!meta||!["arma","armadura","acessorio"].includes(meta.type))result={text:"Informe uma arma, armadura ou acessório válido.",changed:false};else if(itemCount(user,item)<1)result={text:`Você não possui \`${item}\`.`,changed:false};else{user.equipamentos[meta.type]=item;rebuildEquipmentBonus(user);result={text:`\`${item}\` equipado no slot ${meta.type}.`,changed:true};}}
else if(def.kind==="unequip"){const slot=String(args[0]||"").toLowerCase();if(!["arma","armadura","acessorio"].includes(slot))result={text:"Use `arma`, `armadura` ou `acessorio`.",changed:false};else{user.equipamentos[slot]=null;rebuildEquipmentBonus(user);result={text:`Slot ${slot} removido.`,changed:true};}}
else if(def.kind==="pay"){const target=requireTargetUser(db,msg);const amount=Math.max(1,Math.floor(Number(args.find((x)=>/^\d+$/.test(x)))||0));if(target.error)result={text:target.error,changed:false};else if(!amount)result={text:`Use \`${prefix}pagar @jogador valor\`.`,changed:false};else if(target.id===id)result={text:"Você não pode transferir para si mesmo.",changed:false};else if(user.gold<amount)result={text:"Gold insuficiente.",changed:false};else{user.gold-=amount;target.user.gold+=amount;result={text:`Você transferiu ${amount} gold para ${fmtUser(target.user)}.`,changed:true};}}
else if(def.kind==="deposit"){const amount=Math.max(1,Math.floor(Number(args[0])||0));if(!amount)result={text:`Use \`${prefix}depositar valor\`.`,changed:false};else if(user.gold<amount)result={text:"Gold insuficiente na carteira.",changed:false};else{user.gold-=amount;user.banco+=amount;result={text:`Depositados ${amount} gold. Banco: ${user.banco}.`,changed:true};}}
else if(def.kind==="withdraw"){const amount=Math.max(1,Math.floor(Number(args[0])||0));if(!amount)result={text:`Use \`${prefix}sacar valor\`.`,changed:false};else if(user.banco<amount)result={text:"Saldo bancário insuficiente.",changed:false};else{user.banco-=amount;user.gold+=amount;result={text:`Sacados ${amount} gold. Banco: ${user.banco}.`,changed:true};}}
else if(def.kind==="bank")result={text:`🏦 Banco: ${user.banco} gold\n💰 Carteira: ${user.gold} gold`,changed:false};
else if(def.kind==="tradeitem"){const target=requireTargetUser(db,msg);const item=String(args.find((x)=>ITEMS[String(x).toLowerCase()])||"").toLowerCase();const qty=Math.max(1,Math.floor(Number(args.find((x)=>/^\d+$/.test(x)))||1));if(target.error)result={text:target.error,changed:false};else if(!item)result={text:`Use \`${prefix}trocaritem @jogador item quantidade\`.`,changed:false};else if(!removeItem(user,item,qty))result={text:`Você não possui \`${item}\` x${qty}.`,changed:false};else{addItem(target.user,item,qty);result={text:`Transferido \`${item}\` x${qty} para ${fmtUser(target.user)}.`,changed:true};}}
else if(def.kind==="market"){const rows=db.mercado.slice(0,20);result={text:`🛒 *MERCADO*\n${rows.length?rows.map((l)=>`• #${l.id} — \`${l.item}\` x${l.qty} — ${l.price} gold`).join("\n"):"• sem anúncios"}`,changed:false};}
else if(def.kind==="listmarket"){const item=String(args[0]||"").toLowerCase();const qty=Math.max(1,Math.floor(Number(args[1])||1));const price=Math.max(1,Math.floor(Number(args[2])||0));if(!ITEMS[item]||!price)result={text:`Use \`${prefix}anunciaritem item quantidade preco\`.`,changed:false};else if(!removeItem(user,item,qty))result={text:`Você não possui \`${item}\` x${qty}.`,changed:false};else{const listing={id:Date.now().toString(36).slice(-7),seller:id,item,qty,price,at:Date.now()};db.mercado.push(listing);result={text:`Anúncio #${listing.id} criado: \`${item}\` x${qty} por ${price} gold.`,changed:true};}}
else if(def.kind==="buymarket"){const lid=String(args[0]||"").replace(/^#/,"");const l=db.mercado.find((x)=>x.id===lid);if(!l)result={text:"Anúncio não encontrado.",changed:false};else if(l.seller===id)result={text:"Você não pode comprar seu próprio anúncio.",changed:false};else if(user.gold<l.price)result={text:"Gold insuficiente.",changed:false};else{user.gold-=l.price;addItem(user,l.item,l.qty);if(db.usuarios[l.seller]){db.usuarios[l.seller]=normalizeUser(db.usuarios[l.seller],l.seller);db.usuarios[l.seller].gold+=l.price;}db.mercado=db.mercado.filter((x)=>x!==l);result={text:`Compra do anúncio #${lid} concluída.`,changed:true};}}
else if(def.kind==="cancelmarket"){const lid=String(args[0]||"").replace(/^#/,"");const l=db.mercado.find((x)=>x.id===lid&&x.seller===id);if(!l)result={text:"Anúncio próprio não encontrado.",changed:false};else{addItem(user,l.item,l.qty);db.mercado=db.mercado.filter((x)=>x!==l);result={text:`Anúncio #${lid} cancelado e itens devolvidos.`,changed:true};}}
else if(def.kind==="craft"){const name=String(args[0]||"").toLowerCase();const recipe=RECIPES[name];if(!recipe)result={text:`Receita inválida. Use \`${prefix}receitas\`.`,changed:false};else{const missing=Object.entries(recipe.ingredients).find(([i,q])=>itemCount(user,i)<q);if(missing)result={text:`Falta \`${missing[0]}\` x${missing[1]}.`,changed:false};else{for(const[i,q]of Object.entries(recipe.ingredients))removeItem(user,i,q);addItem(user,name,recipe.amount);user.stats.crafts+=1;user.stats.acoes+=1;gainXp(user,35);result={text:`Craft concluído: \`${name}\` x${recipe.amount}.`,changed:true};}}}
else if(def.kind==="dismantle"){const item=String(args[0]||"").toLowerCase();const meta=ITEMS[item];if(!meta||!["arma","armadura","acessorio"].includes(meta.type))result={text:"Escolha um equipamento da mochila.",changed:false};else if(!removeItem(user,item,1))result={text:`Você não possui \`${item}\`.`,changed:false};else{const qty=Math.max(1,Math.floor(meta.price/250));addItem(user,"sucata",qty);if(meta.rarity!=="comum")addItem(user,"cristal",1);result={text:`\`${item}\` desmontado em materiais.`,changed:true};}}
else if(def.kind==="repair"){const slot=String(args[0]||"arma").toLowerCase();const item=user.equipamentos[slot];if(!item)result={text:`Nenhum item equipado no slot \`${slot}\`.`,changed:false};else if(user.gold<100)result={text:"São necessários 100 gold.",changed:false};else{user.gold-=100;result={text:`${item} foi revisado e reparado por 100 gold.`,changed:true};}}
else if(def.kind==="reforge"){const slot=String(args[0]||"arma").toLowerCase();const item=user.equipamentos[slot];if(!item)result={text:`Nenhum item equipado no slot \`${slot}\`.`,changed:false};else if(user.gold<500)result={text:"São necessários 500 gold.",changed:false};else{user.gold-=500;if(slot==="arma")user.dano+=1;else if(slot==="armadura")user.defesa+=1;else user.agilidade+=1;result={text:`${item} foi reforjado. Seu atributo principal aumentou em 1.`,changed:true};}}
else if(def.kind==="train"){const wait=cooldown(user,"treinar",1800000);if(wait)result={text:`Treino disponível em ${formatMs(wait)}.`,changed:true};else{const x=randomInt(70,130);gainXp(user,x);user.stats.acoes+=1;result={text:`Treino concluído: +${x} XP.`,changed:true};}}
else if(def.kind==="restore"){const wait=cooldown(user,def.name,def.cooldown||600000);if(wait)result={text:`Disponível em ${formatMs(wait)}.`,changed:true};else{if(def.resource==="mana")user.mana=Math.min(user.manaMax,user.mana+def.amount);else user.vida=Math.min(user.vidaMax,user.vida+def.amount);result={text:`Recuperação concluída. Vida ${user.vida}/${user.vidaMax}; mana ${user.mana}/${user.manaMax}.`,changed:true};}}
else if(def.kind==="rest"){const wait=cooldown(user,"descansar",1200000);if(wait)result={text:`Você poderá descansar novamente em ${formatMs(wait)}.`,changed:true};else{user.vida=user.vidaMax;user.mana=user.manaMax;user.stamina=user.staminaMax;result={text:"Descanso completo: vida, mana e stamina restauradas.",changed:true};}}
else if(def.kind==="manaheal"){if(user.gold<60)result={text:"São necessários 60 gold.",changed:false};else{user.gold-=60;user.mana=Math.min(user.manaMax,user.mana+30);result={text:`Mana recuperada para ${user.mana}/${user.manaMax}.`,changed:true};}}
else if(def.kind==="upgrade"){if(user.gold<def.cost)result={text:`São necessários ${def.cost} gold.`,changed:false};else{user.gold-=def.cost;user[def.stat]=(Number(user[def.stat])||0)+def.amount;if(def.stat==="vidaMax")user.vida+=def.amount;if(def.stat==="manaMax")user.mana+=def.amount;result={text:`${def.stat} aumentou em ${def.amount}.`,changed:true};}}
else if(def.kind==="classes")result={text:`🧙 *CLASSES*\n${Object.entries(CLASSES).map(([n,c])=>`• \`${n}\` — ${c.text}`).join("\n")}`,changed:false};
else if(def.kind==="changeclass"){const name=String(args[0]||"").toLowerCase();const c=CLASSES[name];if(!c)result={text:`Escolha: ${Object.keys(CLASSES).map((x)=>`\`${x}\``).join(" · ")}`,changed:false};else if(user.gold<800)result={text:"Trocar de classe custa 800 gold.",changed:false};else{user.gold-=800;user.classe=name[0].toUpperCase()+name.slice(1);user.dano+=c.dano;user.defesa+=c.defesa;user.agilidade+=c.agilidade;user.manaMax+=c.mana;user.mana=Math.min(user.manaMax,user.mana+c.mana);result={text:`Classe alterada para ${user.classe}.`,changed:true};}}
else if(def.kind==="specialization"){const spec=String(args[0]||"").toLowerCase();const options=["assalto","defesa","arcano","precisao","suporte"];if(!options.includes(spec))result={text:`Escolha: ${options.map((x)=>`\`${x}\``).join(" · ")}`,changed:false};else if(user.level<10)result={text:"Especializações exigem level 10.",changed:false};else{user.especializacao=spec;result={text:`Especialização definida como ${spec}.`,changed:true};}}
else if(def.kind==="learn"){const skill=String(args[0]||"").toLowerCase();const s=SKILLS[skill];if(!s)result={text:`Habilidades: ${Object.keys(SKILLS).map((x)=>`\`${x}\``).join(" · ")}`,changed:false};else if(user.habilidades.includes(skill))result={text:"Essa habilidade já foi aprendida.",changed:false};else if(user.level<s.minLevel)result={text:`Exige level ${s.minLevel}.`,changed:false};else if(user.gold<s.cost)result={text:`Exige ${s.cost} gold.`,changed:false};else{user.gold-=s.cost;user.habilidades.push(skill);result={text:`Habilidade \`${skill}\` aprendida.`,changed:true};}}
else if(def.kind==="evolve"){if(!removeItem(user,"essencia",1))result={text:"Você precisa de `essencia` x1.",changed:false};else{user.vidaMax+=10;user.manaMax+=5;user.dano+=2;user.defesa+=2;result={text:"Essência consumida: vida, mana, dano e defesa evoluíram.",changed:true};}}
else if(def.kind==="prestige"){if(user.level<50)result={text:"Prestígio exige level 50.",changed:false};else{user.prestigio+=1;user.level=1;user.xp=0;user.dano+=5;user.defesa+=5;user.vidaMax+=20;user.manaMax+=10;checkAchievements(user);result={text:`Prestígio ${user.prestigio} alcançado. Level reiniciado com bônus permanentes.`,changed:true};}}
else if(def.kind==="title")result={text:`Título ativo: ${user.tituloAtivo}\nDisponíveis: ${user.titulos.map((t)=>`\`${t}\``).join(" · ")}`,changed:false};
else if(def.kind==="equiptitle"){const wanted=args.join(" ").trim();const found=user.titulos.find((t)=>t.toLowerCase()===wanted.toLowerCase());if(!found)result={text:"Título não desbloqueado.",changed:false};else{user.tituloAtivo=found;result={text:`Título equipado: ${found}.`,changed:true};}}
else if(def.kind==="rename"){const name=args.join(" ").trim().replace(/[\r\n]/g," ").slice(0,30);if(name.length<2)result={text:`Use \`${prefix}renome Novo Nome\`.`,changed:false};else if(user.gold<100)result={text:"Renomear custa 100 gold.",changed:false};else{user.gold-=100;user.rpgNome=name;user.renome+=1;result={text:`Nome do RPG alterado para ${name}.`,changed:true};}}
else if(def.kind==="explore")result=adventureAction(def,user,cfg);
else if(def.kind==="travel"){const zone=String(args[0]||"").toLowerCase();if(!ZONES[zone])result={text:`Destinos: ${Object.keys(ZONES).map((z)=>`\`${z}\``).join(" · ")}`,changed:false};else if(user.level<ZONES[zone])result={text:`${zone} exige level ${ZONES[zone]}.`,changed:false};else{user.zona=zone;result={text:`Você viajou para ${zone}.`,changed:true};}}
else if(def.kind==="dungeon"){const wait=cooldown(user,"masmorra",3600000);if(wait)result={text:`Masmorra disponível em ${formatMs(wait)}.`,changed:true};else{const r=reward(user,randomInt(220,420),randomInt(150,260),cfg);addItem(user,Math.random()<0.5?"ferro":"cristal",randomInt(1,3));user.stats.exploracoes+=1;result={text:`Masmorra concluída: +${r.gold} gold e +${r.xp} XP.`,changed:true};}}
else if(def.kind==="expedition"){const wait=cooldown(user,"expedicao",7200000);if(wait)result={text:`Expedição disponível em ${formatMs(wait)}.`,changed:true};else{const r=reward(user,randomInt(350,650),randomInt(220,380),cfg);addItem(user,"bau",1);user.stats.exploracoes+=2;result={text:`Expedição concluída: +${r.gold} gold, +${r.xp} XP e \`bau\` x1.`,changed:true};}}
else if(["patrol","investigate","treasure","track","elite"].includes(def.kind)){const table={patrol:{gold:[50,120],xp:[30,60],item:"sucata",key:"patrulhar",cd:600000},investigate:{gold:[40,100],xp:[40,80],item:"fragmento",key:"investigar",cd:900000},treasure:{gold:[80,180],xp:[45,90],item:"bau",key:"procurartesouro",cd:1800000},track:{gold:[30,75],xp:[35,70],item:"erva-rara",key:"rastrear",cd:900000},elite:{gold:[180,360],xp:[130,230],item:"essencia",key:"cacaelite",cd:2700000}}[def.kind];const wait=cooldown(user,table.key,table.cd);if(wait)result={text:`Disponível em ${formatMs(wait)}.`,changed:true};else{const r=reward(user,randomInt(...table.gold),randomInt(...table.xp),cfg);addItem(user,table.item,1);user.stats.acoes+=1;result={text:`Ação concluída: +${r.gold} gold, +${r.xp} XP e \`${table.item}\` x1.`,changed:true};}}
else if(def.kind==="openchest"){if(!removeItem(user,"bau",1))result={text:"Você não possui `bau`.",changed:false};else{const g=randomInt(150,450);user.gold+=g;const rare=Math.random()<0.25?"essencia":"cristal";addItem(user,rare,1);result={text:`Baú aberto: ${g} gold e \`${rare}\` x1.`,changed:true};}}
else if(def.kind==="camp"){const wait=cooldown(user,"acampar",1800000);if(wait)result={text:`Acampamento disponível em ${formatMs(wait)}.`,changed:true};else{user.vida=Math.min(user.vidaMax,user.vida+50);user.mana=Math.min(user.manaMax,user.mana+25);user.stamina=user.staminaMax;result={text:"Acampamento concluído: recursos recuperados.",changed:true};}}
else if(def.kind==="cook"){if(itemCount(user,"peixe")<1||itemCount(user,"erva")<1)result={text:"Cozinhar exige `peixe` x1 e `erva` x1.",changed:false};else{removeItem(user,"peixe",1);removeItem(user,"erva",1);addItem(user,"refeicao",2);result={text:"Você preparou `refeicao` x2.",changed:true};}}
else if(def.kind==="eventinfo"){const e=db.eventoGlobal?.name?db.eventoGlobal:null;result={text:e?`Evento global: ${e.name}\nBônus: ${e.bonus||"recompensas especiais"}`:"Nenhum evento global ativo.",changed:false};}
else if(def.kind==="battle"){if(user.vida<=0)result={text:`Você precisa usar \`${prefix}reviver\` antes de lutar.`,changed:false};else if(user.combate)result={text:`Já existe um combate. Use \`${prefix}combateinfo\`.`,changed:false};else{const m=monsterForLevel(user.level);user.combate={enemy:m.name,hp:m.hp,maxHp:m.hp,attack:m.attack,gold:m.gold,xp:m.xp,defending:false,dodge:false};user.stats.batalhas+=1;result={text:`Batalha iniciada contra ${m.name} (${m.hp} HP). Use \`${prefix}atacar\`, \`${prefix}defender\`, \`${prefix}esquivar\` ou \`${prefix}habilidade\`.`,changed:true};}}
else if(def.kind==="attack"){const c=user.combate;if(!c)result={text:`Nenhum combate ativo. Use \`${prefix}batalhar\`.`,changed:false};else{let dmg=Math.max(1,effectiveAttack(user)+randomInt(-3,6));const crit=Math.random()<(user.critico/100);if(crit)dmg=Math.floor(dmg*1.7);c.hp=Math.max(0,c.hp-dmg);if(c.hp<=0){const r=reward(user,c.gold,c.xp,cfg);user.stats.vitorias+=1;user.combate=null;result={text:`Vitória! Você causou ${dmg}${crit?" crítico":""} e recebeu ${r.gold} gold + ${r.xp} XP.`,changed:true};}else{const incoming=enemyStrike(user,c);if(user.vida<=0){user.stats.derrotas+=1;user.combate=null;result={text:`Você causou ${dmg}, mas foi derrotado. Use \`${prefix}reviver\`.`,changed:true};}else result={text:`Você causou ${dmg}${crit?" crítico":""}. Inimigo: ${c.hp}/${c.maxHp} HP. Você recebeu ${incoming}; vida ${user.vida}/${user.vidaMax}.`,changed:true};}}}
else if(def.kind==="defend"){if(!user.combate)result={text:"Nenhum combate ativo.",changed:false};else{user.combate.defending=true;const incoming=enemyStrike(user,user.combate);result={text:`Postura defensiva usada. Dano recebido: ${incoming}. Vida ${user.vida}/${user.vidaMax}.`,changed:true};}}
else if(def.kind==="dodge"){if(!user.combate)result={text:"Nenhum combate ativo.",changed:false};else{user.combate.dodge=true;const incoming=enemyStrike(user,user.combate);result={text:incoming===0?"Esquiva bem-sucedida.":`Esquiva falhou; dano recebido: ${incoming}.`,changed:true};}}
else if(def.kind==="skill"){if(!user.combate)result={text:"Nenhum combate ativo.",changed:false};else{const name=String(args[0]||user.habilidades[0]||"").toLowerCase();const s=SKILLS[name];if(!s||!user.habilidades.includes(name))result={text:"Habilidade não aprendida.",changed:false};else if(user.mana<s.mana)result={text:"Mana insuficiente.",changed:false};else{user.mana-=s.mana;if(s.defense){user.combate.defending=true;result={text:`\`${name}\` ativada: defesa temporária aumentada.`,changed:true};}else{const dmg=Math.floor(effectiveAttack(user)*s.power);user.combate.hp=Math.max(0,user.combate.hp-dmg);if(user.combate.hp<=0){const r=reward(user,user.combate.gold,user.combate.xp,cfg);user.stats.vitorias+=1;user.combate=null;result={text:`\`${name}\` venceu o combate: +${r.gold} gold, +${r.xp} XP.`,changed:true};}else result={text:`\`${name}\` causou ${dmg}. Inimigo: ${user.combate.hp}/${user.combate.maxHp} HP.`,changed:true};}}}}
else if(def.kind==="flee"){if(!user.combate)result={text:"Nenhum combate ativo.",changed:false};else if(Math.random()<0.7){user.combate=null;result={text:"Você saiu do combate com sucesso.",changed:true};}else{const incoming=enemyStrike(user,user.combate);result={text:`A fuga falhou. Dano recebido: ${incoming}.`,changed:true};}}
else if(def.kind==="bossinfo"){if(!db.bosses[from]||db.bosses[from].hp<=0){const b=clone(BOSSES[randomInt(0,BOSSES.length-1)]);db.bosses[from]={...b,maxHp:b.hp,participants:{},spawnedAt:Date.now()};}const b=db.bosses[from];result={text:`👑 Boss: ${b.name}\nHP: ${b.hp}/${b.maxHp}\nUse \`${prefix}atacarboss\`.`,changed:true};}
else if(def.kind==="bossattack"){const b=db.bosses[from];if(!b||b.hp<=0)result={text:`Nenhum boss ativo. Use \`${prefix}boss\`.`,changed:false};else{const wait=cooldown(user,"atacarboss",30000);if(wait)result={text:`Ataque disponível em ${formatMs(wait)}.`,changed:true};else{let dmg=Math.max(5,effectiveAttack(user)+randomInt(0,15));b.hp=Math.max(0,b.hp-dmg);b.participants[id]=(b.participants[id]||0)+dmg;user.stats.bossDamage+=dmg;if(b.hp<=0){const r=reward(user,b.reward,b.xp,cfg);addItem(user,"essencia",1);result={text:`Boss derrotado! Seu golpe causou ${dmg}. Recompensa: ${r.gold} gold, ${r.xp} XP e \`essencia\` x1.`,changed:true};}else result={text:`Você causou ${dmg} no boss. HP: ${b.hp}/${b.maxHp}.`,changed:true};}}}
else if(def.kind==="raidinfo"){if(!db.raids[from]||db.raids[from].hp<=0)db.raids[from]={name:"Guardião da Raid",hp:3000,maxHp:3000,participants:[],damage:{},createdAt:Date.now()};const r=db.raids[from];result={text:`⚔️ Raid: ${r.name}\nHP: ${r.hp}/${r.maxHp}\nParticipantes: ${r.participants.length}\nUse \`${prefix}entrarraid\`.`,changed:true};}
else if(def.kind==="joinraid"){const r=db.raids[from];if(!r||r.hp<=0)result={text:`Use \`${prefix}raid\` para iniciar a raid.`,changed:false};else if(r.participants.includes(id))result={text:"Você já está na raid.",changed:false};else{r.participants.push(id);result={text:"Você entrou na raid.",changed:true};}}
else if(def.kind==="raidattack"){const r=db.raids[from];if(!r||!r.participants.includes(id)||r.hp<=0)result={text:"Entre em uma raid ativa primeiro.",changed:false};else{const wait=cooldown(user,"atacarraid",20000);if(wait)result={text:`Ataque disponível em ${formatMs(wait)}.`,changed:true};else{const dmg=effectiveAttack(user)+randomInt(5,20);r.hp=Math.max(0,r.hp-dmg);r.damage[id]=(r.damage[id]||0)+dmg;if(r.hp<=0){const rr=reward(user,1000,600,cfg);addItem(user,"bau",2);result={text:`Raid concluída! +${rr.gold} gold, +${rr.xp} XP e \`bau\` x2.`,changed:true};}else result={text:`Dano na raid: ${dmg}. HP restante: ${r.hp}/${r.maxHp}.`,changed:true};}}}
else if(def.kind==="challenge"){if(!cfg.pvp)result={text:"PvP está desativado neste grupo.",changed:false};else{const t=requireTargetUser(db,msg);if(t.error)result={text:t.error,changed:false};else if(t.id===id)result={text:"Escolha outro jogador.",changed:false};else{db.duelos[t.id]={from:id,group:from,at:Date.now()};result={text:`Desafio enviado para ${fmtUser(t.user)}. O jogador pode usar \`${prefix}duelo\`.`,changed:true};}}}
else if(def.kind==="duel"){const pending=db.duelos[id];if(!pending)result={text:`Nenhum desafio pendente. Use \`${prefix}desafiar @jogador\`.`,changed:false};else if(!db.usuarios[pending.from]){delete db.duelos[id];result={text:"O desafiante não está mais disponível.",changed:true};}else{const other=normalizeUser(db.usuarios[pending.from],pending.from);const a=effectiveAttack(user)+effectiveDefense(user)+user.agilidade+randomInt(0,35);const b=effectiveAttack(other)+effectiveDefense(other)+other.agilidade+randomInt(0,35);const winner=a>=b?user:other;const loser=a>=b?other:user;winner.stats.duelosV+=1;loser.stats.duelosD+=1;reward(winner,150,90,cfg);delete db.duelos[id];result={text:`Duelo concluído. Vencedor: ${fmtUser(winner)}.`,changed:true};}}
else if(def.kind==="arena"){const rows=Object.values(db.usuarios).map((u)=>normalizeUser(u,u.lid||"")).sort((a,b)=>b.stats.duelosV-a.stats.duelosV).slice(0,10);result={text:`🏟️ *ARENA*\n${rows.map((u,i)=>`${i+1}. ${fmtUser(u)} — ${u.stats.duelosV} vitórias`).join("\n")||"Sem dados."}`,changed:false};}
else if(def.kind==="pvpstats")result={text:`PvP: ${user.stats.duelosV} vitórias / ${user.stats.duelosD} derrotas.`,changed:false};
else if(def.kind==="target"){const pending=db.duelos[id];result={text:pending&&db.usuarios[pending.from]?`Desafio pendente de ${fmtUser(db.usuarios[pending.from])}.`:user.combate?`Alvo atual: ${user.combate.enemy}.`:"Nenhum alvo atual.",changed:false};}
else if(def.kind==="combatinfo"){const c=user.combate;result={text:c?`⚔️ ${c.enemy}\nHP inimigo: ${c.hp}/${c.maxHp}\nSua vida: ${user.vida}/${user.vidaMax}\nSua mana: ${user.mana}/${user.manaMax}`:"Nenhum combate ativo.",changed:false};}
else if(def.kind==="revive"){if(user.vida>0)result={text:"Seu personagem já está pronto para agir.",changed:false};else{user.vida=Math.max(1,Math.floor(user.vidaMax*0.5));user.mana=Math.floor(user.manaMax*0.5);result={text:`Personagem recuperado com ${user.vida}/${user.vidaMax} de vida.`,changed:true};}}
else if(def.kind==="potion"){if(!removeItem(user,"pocao",1))result={text:"Você não possui `pocao`.",changed:false};else{user.vida=Math.min(user.vidaMax,user.vida+40);result={text:`Poção usada. Vida: ${user.vida}/${user.vidaMax}.`,changed:true};}}
else if(def.kind==="protect"){if(user.mana<15)result={text:"Mana insuficiente; são necessários 15.",changed:false};else{user.mana-=15;user.buffs.push({name:"proteção",defense:6,until:Date.now()+120000});result={text:"Proteção ativada por 2 minutos: +6 de defesa temporária.",changed:true};}}
else if(def.kind==="guild"){if(!user.guilda||!db.guildas[user.guilda])result={text:`Você não está em guilda. Use \`${prefix}criarguilda nome\` ou \`${prefix}entrarguilda nome\`.`,changed:false};else{const g=db.guildas[user.guilda];result={text:`🏰 *${g.name}*\n• membros: ${g.members.length}\n• banco: ${g.bank} gold\n• líder: ${db.usuarios[g.leader]?fmtUser(db.usuarios[g.leader]):g.leader}`,changed:false};}}
else if(def.kind==="createguild"){const name=args.join(" ").trim().slice(0,30);if(user.guilda)result={text:"Saia da guilda atual primeiro.",changed:false};else if(name.length<3)result={text:`Use \`${prefix}criarguilda Nome da Guilda\`.`,changed:false};else if(user.gold<1000)result={text:"Criar guilda custa 1000 gold.",changed:false};else{const existing=Object.values(db.guildas).find((g)=>g.name.toLowerCase()===name.toLowerCase());if(existing)result={text:"Esse nome já está em uso.",changed:false};else{user.gold-=1000;const gid=Date.now().toString(36).slice(-6);db.guildas[gid]={id:gid,name,leader:id,members:[id],bank:0,createdAt:Date.now()};user.guilda=gid;result={text:`Guilda ${name} criada com id \`${gid}\`.`,changed:true};}}}
else if(def.kind==="joinguild"){const query=args.join(" ").trim().toLowerCase();if(user.guilda)result={text:"Você já está em uma guilda.",changed:false};else{const g=Object.values(db.guildas).find((x)=>x.id===query||x.name.toLowerCase()===query);if(!g)result={text:"Guilda não encontrada.",changed:false};else{g.members.push(id);user.guilda=g.id;result={text:`Você entrou em ${g.name}.`,changed:true};}}}
else if(def.kind==="leaveguild"){if(!user.guilda||!db.guildas[user.guilda])result={text:"Você não está em guilda.",changed:false};else{const g=db.guildas[user.guilda];if(g.leader===id&&g.members.length>1)result={text:"O líder precisa ser o último membro para sair.",changed:false};else{g.members=g.members.filter((x)=>x!==id);user.guilda=null;if(!g.members.length)delete db.guildas[g.id];result={text:"Você saiu da guilda.",changed:true};}}}
else if(def.kind==="guildmembers"){if(!user.guilda||!db.guildas[user.guilda])result={text:"Você não está em guilda.",changed:false};else{const g=db.guildas[user.guilda];result={text:`👥 *MEMBROS — ${g.name}*\n${g.members.map((mid)=>`• ${db.usuarios[mid]?fmtUser(db.usuarios[mid]):mid}`).join("\n")}`,changed:false};}}
else if(def.kind==="guildrank"){const rows=Object.values(db.guildas).sort((a,b)=>b.bank-a.bank).slice(0,10);result={text:`🏰 *RANK GUILDAS*\n${rows.map((g,i)=>`${i+1}. ${g.name} — ${g.bank} gold`).join("\n")||"Sem guildas."}`,changed:false};}
else if(def.kind==="guilddonate"){const amount=Math.max(1,Math.floor(Number(args[0])||0));if(!user.guilda||!db.guildas[user.guilda])result={text:"Você não está em guilda.",changed:false};else if(!amount||user.gold<amount)result={text:"Valor inválido ou gold insuficiente.",changed:false};else{user.gold-=amount;db.guildas[user.guilda].bank+=amount;result={text:`Doação de ${amount} gold realizada.`,changed:true};}}
else if(def.kind==="questlist")result={text:`📜 *MISSÕES*\n${Object.entries(QUESTS).map(([qid,q])=>`• \`${qid}\` — ${q.label}: ${q.target} ${q.stat}; recompensa ${q.gold}g/${q.xp}xp`).join("\n")}`,changed:false};
else if(def.kind==="questaccept"){const qid=String(args[0]||"").toLowerCase();const q=QUESTS[qid];if(!q)result={text:`Use \`${prefix}missao\` para ver IDs.`,changed:false};else if(user.missaoAtiva)result={text:"Você já possui missão ativa.",changed:false};else{user.missaoAtiva={id:qid,label:q.label,stat:q.stat,target:q.target,base:user.stats[q.stat]||0,gold:q.gold,xp:q.xp};result={text:`Missão aceita: ${q.label}.`,changed:true};}}
else if(def.kind==="questabandon"){if(!user.missaoAtiva)result={text:"Nenhuma missão ativa.",changed:false};else{user.missaoAtiva=null;result={text:"Missão abandonada.",changed:true};}}
else if(def.kind==="questturnin"){const q=user.missaoAtiva;if(!q)result={text:"Nenhuma missão ativa.",changed:false};else{const progress=(user.stats[q.stat]||0)-q.base;if(progress<q.target)result={text:`Missão incompleta: ${progress}/${q.target}.`,changed:false};else{const r=reward(user,q.gold,q.xp,cfg);user.missaoAtiva=null;result={text:`Missão entregue: +${r.gold} gold e +${r.xp} XP.`,changed:true};}}}
else if(def.kind==="rewards")result={text:`🎁 *RECOMPENSAS RECENTES*\n${user.recompensasRecentes.length?user.recompensasRecentes.map((r)=>`• +${r.gold}g / +${r.xp}xp`).join("\n"):"• nenhuma"}`,changed:false};
else if(def.kind==="friend"){const t=requireTargetUser(db,msg);if(t.error)result={text:t.error,changed:false};else if(t.id===id)result={text:"Escolha outro jogador.",changed:false};else{if(!user.amigosRpg.includes(t.id))user.amigosRpg.push(t.id);if(!t.user.amigosRpg.includes(id))t.user.amigosRpg.push(id);result={text:`${fmtUser(t.user)} foi adicionado como aliado RPG.`,changed:true};}}
else if(def.kind==="party")result={text:`🧭 *GRUPO DE AVENTURA*\n${user.party.length?user.party.map((pid)=>`• ${db.usuarios[pid]?fmtUser(db.usuarios[pid]):pid}`).join("\n"):"• somente você"}`,changed:false};
else if(def.kind==="inviteparty"){const t=requireTargetUser(db,msg);if(t.error)result={text:t.error,changed:false};else if(t.id===id)result={text:"Escolha outro jogador.",changed:false};else{if(!user.party.includes(t.id))user.party.push(t.id);result={text:`${fmtUser(t.user)} foi adicionado ao seu grupo de aventura.`,changed:true};}}
else if(def.kind==="admininfo"){const active=from?.endsWith("@g.us")?rpgSystem.isRpgAtivo(from):true;const gc=groupConfig(db,from);result={text:`🛠️ *RPG ADMIN*\n• ativo: ${active?"sim":"não"}\n• jogadores: ${Object.keys(db.usuarios).length}\n• guildas: ${Object.keys(db.guildas).length}\n• anúncios: ${db.mercado.length}\n• multiplicador gold: ${gc.goldMultiplier}x\n• multiplicador XP: ${gc.xpMultiplier}x\n• PvP: ${gc.pvp?"on":"off"}`,changed:true};}
else if(def.kind==="adminset"){const key=String(args[0]||"").toLowerCase();const value=String(args[1]||"").toLowerCase();const gc=groupConfig(db,from);if(key==="pvp"&&["on","off"].includes(value)){gc.pvp=value==="on";result={text:`PvP ${value}.`,changed:true};}else if(["gold","xp"].includes(key)){const n=Math.max(0.25,Math.min(5,Number(value)||0));if(!n)result={text:"Use um multiplicador entre 0.25 e 5.",changed:false};else{if(key==="gold")gc.goldMultiplier=n;else gc.xpMultiplier=n;result={text:`Multiplicador ${key} definido em ${n}x.`,changed:true};}}else result={text:`Use \`${prefix}rpgset pvp on|off\`, \`${prefix}rpgset gold 1.5\` ou \`${prefix}rpgset xp 1.5\`.`,changed:false};}
else if(["adminadditem","adminremoveitem","adminreset","adminban","adminunban"].includes(def.kind)){const t=requireTargetUser(db,msg);if(t.error&&def.kind!=="adminunban")result={text:t.error,changed:false};else if(def.kind==="adminadditem"){const item=String(args.find((x)=>ITEMS[String(x).toLowerCase()])||"").toLowerCase();const qty=Math.max(1,Math.floor(Number(args.find((x)=>/^\d+$/.test(x)))||1));if(!item)result={text:"Informe um item válido.",changed:false};else{addItem(t.user,item,qty);result={text:`Adicionado \`${item}\` x${qty} para ${fmtUser(t.user)}.`,changed:true};}}else if(def.kind==="adminremoveitem"){const item=String(args.find((x)=>ITEMS[String(x).toLowerCase()])||"").toLowerCase();const qty=Math.max(1,Math.floor(Number(args.find((x)=>/^\d+$/.test(x)))||1));if(!item||!removeItem(t.user,item,qty))result={text:"Item/quantidade indisponível.",changed:false};else result={text:`Removido \`${item}\` x${qty} de ${fmtUser(t.user)}.`,changed:true};}else if(def.kind==="adminreset"){if(String(args.at(-1)||"").toLowerCase()!=="confirmar")result={text:`Use \`${prefix}rpgreset @jogador confirmar\`.`,changed:false};else{delete db.usuarios[t.id];result={text:"Ficha RPG resetada.",changed:true};}}else if(def.kind==="adminban"){db.rpgBans[t.id]={at:Date.now(),by:id};result={text:`${fmtUser(t.user)} foi bloqueado no RPG.`,changed:true};}else if(def.kind==="adminunban"){const tid=targetId(msg);if(!tid)result={text:"Marque o jogador.",changed:false};else{delete db.rpgBans[tid];result={text:"Bloqueio RPG removido.",changed:true};}}}
else if(def.kind==="adminevent"){const text=args.join(" ").trim();if(!text)result={text:`Use \`${prefix}rpgevento Nome do evento\` ou \`${prefix}rpgevento off\`.`,changed:false};else if(text.toLowerCase()==="off"){db.eventoGlobal={};result={text:"Evento global encerrado.",changed:true};}else{db.eventoGlobal={name:text.slice(0,60),bonus:"recompensas e exploração ampliadas",at:Date.now(),by:id};result={text:`Evento global criado: ${text.slice(0,60)}.`,changed:true};}}
else result={text:"Comando RPG ainda não implementado corretamente.",changed:false};

if(user){user.stats.acoes+=result?.changed&&!["gather","collect","train","explore"].includes(def.kind)?1:0;const achievements=checkAchievements(user);if(achievements.length&&result)result.text+=`\n🏆 Novo título: ${achievements.join(", ")}.`;db.usuarios[id]=user;}if(result?.changed)saveDb(db);return send(conn,from,msg,result?.text||"Ação concluída.");}

module.exports={execute,executeDefinition:execute,loadDb,saveDb,normalizeUser,senderId,targetId,addItem,removeItem,itemCount,ITEMS,RECIPES,CLASSES,SKILLS,QUESTS,ZONES,MONSTERS,BOSSES,LEGACY_COMMANDS,stylize};
